---
- name: Playbook to build docker image for CD/CD demonstrations
  hosts: localhost
  gather_facts: False

  tasks:
    - name: create build directory
      file:
        path: /root/restful-pyapp
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: copy Dockerfile
      copy:
      src: ./Dockerfile
      dest: /root/restful-pyapp/Dockerfile
      owner: root
      group: root
      mode: '0644'
    - name: build image
      docker_image:
        name: games-api:latest
        build:
          path: /root/restful-pyapp
          source: build
        state: present